### PR TITLE
Feature/account page

### PR DESCRIPTION
**Pull request by rikkriuk**
## Enhancement

- Add layouting for account page
- Routing integration for sidebar account
- Responsive implementation desing

## References

- Design: [Desktop](https://www.figma.com/design/k9F0WnIhzuQ00wDPYLl7FG/Final-Project-E-Commerce-Website?node-id=814-4691&t=i3y0jEXCILteQa5s-4)
- Trello Ticket: [Ticket](https://trello.com/c/03OvXSMC)

### CODE REVIEW

**Comment by ignasiusadhitia** [comment]
kang @rikkriuk salah sasaran, branch tujuan ke development

**Comment by ignasiusadhitia** [comment]
Link preview

https://final-project-front-git-featur-20d8ca-ignasiusadhitias-projects.vercel.app/?_vercel_share=yAC8AFKjdTgdZnfHjFnpnDhBDbYFaPSc

**Review by desup1421 — APPROVED** [review]
Good job!

**Review by ignasiusadhitia — APPROVED** [review]
well done 🚀 🚀 🚀

**Pull request merged**
