### PR TITLE
feat: add seo optimization

### PR DESCRIPTION
**Pull request by ignasiusadhitia**
### Enhancement
---
- Add SEO component
- Add robots.txt
- Add sitemap.xml

### Reference
- Trello Ticket: [Ticket #44](https://trello.com/c/wKJKGOEy)

### CODE REVIEW

**Comment by ignasiusadhitia** [comment]
https://exclusive-store-front-git-feature-seo-ignasiusadhitias-projects.vercel.app/?_vercel_share=dPisQwsTG1A4RefdnSwd99qNW0XstKQb

**Comment by ignasiusadhitia** [comment]
https://exclusive-store-front-git-feature-seo-ignasiusadhitias-projects.vercel.app/?_vercel_share=dPisQwsTG1A4RefdnSwd99qNW0XstKQb

**Comment by ignasiusadhitia** [comment]
https://exclusive-store-front-git-feature-seo-ignasiusadhitias-projects.vercel.app/?_vercel_share=dPisQwsTG1A4RefdnSwd99qNW0XstKQb

**Review by desup1421 — APPROVED** [review]
Good job! 🚀🚀🚀

**Review by rikkriuk — APPROVED** [review]
Good jobs!

**Pull request merged**
