### PR TITLE
Release v.0.0.4

### PR DESCRIPTION
**Pull request by ignasiusadhitia**
### Release
---
- [feat: add protected route, wishlist management and profile update](https://github.com/ignasiusadhitia/final-project-front/pull/26)
- [feat: add crud for address and add logout with translate in mobile device](https://github.com/ignasiusadhitia/final-project-front/pull/27)
- [feature: add user checkout flow simulation](https://github.com/ignasiusadhitia/final-project-front/pull/28)
- [feat: add seo optimization](https://github.com/ignasiusadhitia/final-project-front/pull/23)

### CODE REVIEW

**Comment by ignasiusadhitia** [comment]
https://exclusive-store-front-git-development-ignasiusadhitias-projects.vercel.app/?_vercel_share=D6FvHioaQjuCYokCl5evViHcYFJOqE73

**Review by rikkriuk — APPROVED** [review]
All feature work so well 🚀

**Review by desup1421 — APPROVED** [review]
Excellent! 🚀🚀🚀

**Review by dvpms — APPROVED** [review]
Approve

**Pull request merged**
