### PR TITLE
feature/auth

### PR DESCRIPTION
**Pull request by ignasiusadhitia**
### Enhancement
---
- Add Login Page
- Add Sign Up Page

### References
---
- Design: [Figma](https://www.figma.com/design/k9F0WnIhzuQ00wDPYLl7FG/Final-Project-E-Commerce-Website?node-id=828-5677&t=Vn13pgSU78zUPgA6-4)
- Trello Ticket: [Ticket #6](https://trello.com/c/h5FY6qZ3)

### CODE REVIEW

**Review by desup1421 — DISMISSED** [review]
Excellent work!

**Comment by ignasiusadhitia** [comment]
sudah saya resolve conflictnya ya kang @desup1421

**Comment by desup1421** [comment]
> sudah saya resolve conflictnya ya kang @desup1421

Oke, saya cek.

**Review by desup1421 — APPROVED** [review]
Thank you for resolve the conflict!

**Pull request merged**
